### ISSUE TITLE
Restyle delete facet buttons so they don't push text over

### ISSUE THREAD

**Issue by justcolin** [HTGovdocs/usdocs_registry#28]
This may suffice:
```css
.facets .remove {
  position: absolute;
  right: 100%;
  margin-right: 0.2rem;
}

.facets .facet-label {
  position: relative;
}
```
