### ISSUE TITLE
Add a more clear separation between items in the results list

### ISSUE THREAD

**Issue by justcolin** [HTGovdocs/usdocs_registry#31]
Zebra striping or a border between items using something like:
```css
.documents-list .result + .result {
  border-top: 1px solid;
}
```
