### ISSUE TITLE
Add label to search box

### ISSUE THREAD

**Issue by justcolin** [HTGovdocs/usdocs_registry#36]
Every `<input>` needs a `<label>` and a `for` attribute to pair them. The search box at the top of the page is missing the `<label>`. You can hide it using an accessible hide class such as:

```css
.not_visible {
  position: absolute !important;
  clip: rect(1px 1px 1px 1px) !important;
  clip: rect(1px, 1px, 1px, 1px) !important;
  height: 1px !important;

  width: 1px !important;
  overflow: hidden !important;
  padding: 0 !important;
  margin: 0 !important;
}
```

_It is littered with `!important` because this is one of the few times that a class really does have to just override everything._
